/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import com.formdev.flatlaf.FlatLightLaf;
/**
 *
 * @author angga murdika
 */
public class form_barang extends javax.swing.JFrame {

    /**
     * Creates new form form_barang
     */
    public form_barang() {
        initComponents();
        
        txtNamaBarang.putClientProperty("JTextField.placeholderText", "Masukkan Nama");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lbTab = new javax.swing.JLabel();
        lbKodeBarang = new javax.swing.JLabel();
        lbNamaBarang = new javax.swing.JLabel();
        lbHarga = new javax.swing.JLabel();
        ddKodeBarang = new javax.swing.JComboBox<>();
        sHarga = new javax.swing.JSpinner();
        txtNamaBarang = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTab.setFont(new java.awt.Font("SF Pro Text", 1, 24)); // NOI18N
        lbTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTab.setText("Barang");
        lbTab.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbKodeBarang.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        lbKodeBarang.setText("Kode Barang");

        lbNamaBarang.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        lbNamaBarang.setText("Nama Barang");

        lbHarga.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        lbHarga.setText("Harga");

        ddKodeBarang.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        ddKodeBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Barang", "Item 2", "Item 3", "Item 4" }));
        ddKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddKodeBarangActionPerformed(evt);
            }
        });

        sHarga.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        sHarga.setAlignmentX(0.0F);
        sHarga.setAlignmentY(0.0F);

        txtNamaBarang.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 204, 51));
        btnSimpan.setFont(new java.awt.Font("SF Pro Text", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbKodeBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbHarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ddKodeBarang, 0, 231, Short.MAX_VALUE)
                        .addComponent(sHarga, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNamaBarang)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lbTab)
                .addGap(30, 30, 30)
                .addComponent(lbKodeBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ddKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNamaBarang)
                .addGap(5, 5, 5)
                .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ddKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddKodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddKodeBarangActionPerformed

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> ddKodeBarang;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbKodeBarang;
    private javax.swing.JLabel lbNamaBarang;
    private javax.swing.JLabel lbTab;
    private javax.swing.JSpinner sHarga;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables
}
